### ISSUE TITLE
convertUnit should ideally do two way conversion

### ISSUE THREAD

**Issue by arjunmehta** [manuelbieh/geolib#58]
Hi there, feature request here! :)

It would be ideal if `convertUnit()` would convert other units into meters, instead of just meters into other units.

Reason being, I have an API interface that outputs distances in various desired units, and it should be able to take in distances in other units as well, with my primary logic working in meters.

Thanks for the module!

**Comment by manuelbieh** [comment]
It's just a convenience method. Internally all calculations are done in meters. Since not everybody (especially in the US) is using meters I created this method to be able to get imperial values without any dependencies.

There is an undocumented property `geolib.measures` which you can use to convert units the other way by just a simple division.

Quick example:
```
var miles = 0.621371;
var meters = miles / geolib.measures['mi'];
console.log(meters); // -> 999.9996906240001
```

I will have a look if it might be a good idea to add another option to convertUnit to do two way conversion.
