### ISSUE TITLE
isPointInside clarification

### ISSUE THREAD

**Issue by avermeulen** [manuelbieh/Geolib#64]
The readme file states for the `isPointInside` method that `the polygon coords must be in correct order!`

Can you please clarify what the 'correct' order is and how can I check if my coords are in the correct order.

**Comment by manuelbieh** [comment]
Let's assume the coordinate you want to check is (10,8) and the coordinates you want to check it against are A(2,2), B(2,12), C(18,12) and D(18,2). *Then* (10,8) is *within* your polygon.

If you change the order of your coordinates you will get a different result. I made a small illustration because … a picture is worth a thousand words ;)

**"right" order**
![](http://i.imgur.com/XW1gk9A.png)

**"wrong" order**
![](http://i.imgur.com/AAvjOwI.png)

```
geolib.isPointInside([10,8], [
  [2,2], [2,12], [18,12], [18,2]
]);
```
-> `true`

Same coordinates but different order (C and D flipped):
```
geolib.isPointInside([10,8], [
  [2,2], [2,12], [18,2], [18,12]
]);
```
-> `false`

**Comment by avermeulen** [comment]
Ok thanks that makes sense! You pictures are great! a 1000 words indeed.

**Comment by socieboy** [comment]
What if I provide coordinates for 2 polygons?
