### ISSUE TITLE
computeDestinationPoint is not in npm

### ISSUE THREAD

**Issue by demobiel** [manuelbieh/Geolib#78]
Hi

thank you for this great library.

However, when I install geolib via npm the function computeDestinationPoint is not implemented. The same when I try to install it from github.
I have version  2.0.18 installed, any idea why this function is not there?

Andries

**Comment by manuelbieh** [comment]
It had not been fully implemented and reviewed. Now it is and npm install geolib@2.0.19 should do it. Notice: instead of passing lat and lon as separate parameters to the method you now pass a coordinate object as first parameter. 

Example: 
`geolib.computeDestinationPoint({lat: 51.3, lng: 7.45}, 5000, 180);` 
instead of 
`geolib.computeDestinationPoint(51.3, 7.45, 5000, 180);` 
as it was earlier (in the officially unpublished version of the method).

**Comment by demobiel** [comment]
thanks!
